apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitlab-ce
  name: gitlab-ce-var-opt-claim
  namespace: ci-cd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}