apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab-ce
  name: gitlab-ce
  namespace: ci-cd
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - name: "22"
    port: 22
    targetPort: 22
    nodePort: 32076
  - name: "443"
    port: 443
    targetPort: 443
    nodePort: 30284
  - name: "80"
    nodePort: 31564
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gitlab-ce
